### ISSUE TITLE
[1pt] Choose assets - group task

### ISSUE THREAD

**Issue by dev89s** [dev89s/restaurant-capstone-project#19]
Choose images, text, icons, fonts.

**Comment by skabeo** [comment]
- The images of the following ID were chosen (52854, 53022, 52928, 52995, 52831, 52890)
- Icons was selected for the heart icon `<i class="fa-regular fa-heart"></i>` and `<i id="close-btn" class="fa-solid fa-xmark"></i>` for the close button.
- Font selected was `Comic Neue`.
